name: Positano Sync

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ''
      - run: npm install
      - run: node sync.js
        env:
          ML_TOKEN: ${{ secrets.ML_TOKEN }}
          TN_TOKEN: ${{ secrets.TN_TOKEN }}
          STORE_ID: ${{ secrets.STORE_ID }}